<?php

use Illuminate\Database\Seeder;
use App\Country;

class CountriesTableSeeder extends Seeder
{
    function run()
    {
        DB::table('countries')->truncate();

        $countries = array(
            array('id' => 'AF', 'name' => 'Afghanistan'),
            array('id' => 'ZA', 'name' => 'Afrique du Sud'),
            array('id' => 'AL', 'name' => 'Albanie'),
            array('id' => 'DZ', 'name' => 'Algérie'),
            array('id' => 'DE', 'name' => 'Allemagne'),
            array('id' => 'AD', 'name' => 'Andorre'),
            array('id' => 'AO', 'name' => 'Angola'),
            array('id' => 'AI', 'name' => 'Anguilla'),
            array('id' => 'AQ', 'name' => 'Antarctique'),
            array('id' => 'AG', 'name' => 'Antigua-et-Barbuda'),
            array('id' => 'AN', 'name' => 'Antilles néerlandaises'),
            array('id' => 'SA', 'name' => 'Arabie saoudite'),
            array('id' => 'AR', 'name' => 'Argentine'),
            array('id' => 'AM', 'name' => 'Arménie'),
            array('id' => 'AW', 'name' => 'Aruba'),
            array('id' => 'AU', 'name' => 'Australie'),
            array('id' => 'AT', 'name' => 'Autriche'),
            array('id' => 'AZ', 'name' => 'Azerbaïdjan'),
            array('id' => 'BS', 'name' => 'Bahamas'),
            array('id' => 'BH', 'name' => 'Bahreïn'),
            array('id' => 'BD', 'name' => 'Bangladesh'),
            array('id' => 'BB', 'name' => 'Barbade'),
            array('id' => 'BE', 'name' => 'Belgique'),
            array('id' => 'BZ', 'name' => 'Belize'),
            array('id' => 'BM', 'name' => 'Bermudes'),
            array('id' => 'BT', 'name' => 'Bhoutan'),
            array('id' => 'BO', 'name' => 'Bolivie'),
            array('id' => 'BA', 'name' => 'Bosnie-Herzégovine'),
            array('id' => 'BW', 'name' => 'Botswana'),
            array('id' => 'BN', 'name' => 'Brunéi Darussalam'),
            array('id' => 'BR', 'name' => 'Brésil'),
            array('id' => 'BG', 'name' => 'Bulgarie'),
            array('id' => 'BF', 'name' => 'Burkina Faso'),
            array('id' => 'BI', 'name' => 'Burundi'),
            array('id' => 'BY', 'name' => 'Bélarus'),
            array('id' => 'BJ', 'name' => 'Bénin'),
            array('id' => 'KH', 'name' => 'Cambodge'),
            array('id' => 'CM', 'name' => 'Cameroun'),
            array('id' => 'CA', 'name' => 'Canada'),
            array('id' => 'CV', 'name' => 'Cap-Vert'),
            array('id' => 'CL', 'name' => 'Chili'),
            array('id' => 'CN', 'name' => 'Chine'),
            array('id' => 'CY', 'name' => 'Chypre'),
            array('id' => 'CO', 'name' => 'Colombie'),
            array('id' => 'KM', 'name' => 'Comores'),
            array('id' => 'CG', 'name' => 'Congo'),
            array('id' => 'KP', 'name' => 'Corée du Nord'),
            array('id' => 'KR', 'name' => 'Corée du Sud'),
            array('id' => 'CR', 'name' => 'Costa Rica'),
            array('id' => 'HR', 'name' => 'Croatie'),
            array('id' => 'CU', 'name' => 'Cuba'),
            array('id' => 'CI', 'name' => 'Côte d’Ivoire'),
            array('id' => 'DK', 'name' => 'Danemark'),
            array('id' => 'DJ', 'name' => 'Djibouti'),
            array('id' => 'DM', 'name' => 'Dominique'),
            array('id' => 'SV', 'name' => 'El Salvador'),
            array('id' => 'ES', 'name' => 'Espagne'),
            array('id' => 'EE', 'name' => 'Estonie'),
            array('id' => 'FJ', 'name' => 'Fidji'),
            array('id' => 'FI', 'name' => 'Finlande'),
            array('id' => 'FR', 'name' => 'France'),
            array('id' => 'GA', 'name' => 'Gabon'),
            array('id' => 'GM', 'name' => 'Gambie'),
            array('id' => 'GH', 'name' => 'Ghana'),
            array('id' => 'GI', 'name' => 'Gibraltar'),
            array('id' => 'GD', 'name' => 'Grenade'),
            array('id' => 'GL', 'name' => 'Groenland'),
            array('id' => 'GR', 'name' => 'Grèce'),
            array('id' => 'GP', 'name' => 'Guadeloupe'),
            array('id' => 'GU', 'name' => 'Guam'),
            array('id' => 'GT', 'name' => 'Guatemala'),
            array('id' => 'GG', 'name' => 'Guernesey'),
            array('id' => 'GN', 'name' => 'Guinée'),
            array('id' => 'GQ', 'name' => 'Guinée équatoriale'),
            array('id' => 'GW', 'name' => 'Guinée-Bissau'),
            array('id' => 'GY', 'name' => 'Guyana'),
            array('id' => 'GF', 'name' => 'Guyane française'),
            array('id' => 'GE', 'name' => 'Géorgie'),
            array('id' => 'GS', 'name' => 'Géorgie du Sud et les îles Sandwich du Sud'),
            array('id' => 'HT', 'name' => 'Haïti'),
            array('id' => 'HN', 'name' => 'Honduras'),
            array('id' => 'HU', 'name' => 'Hongrie'),
            array('id' => 'IN', 'name' => 'Inde'),
            array('id' => 'ID', 'name' => 'Indonésie'),
            array('id' => 'IQ', 'name' => 'Irak'),
            array('id' => 'IR', 'name' => 'Iran'),
            array('id' => 'IE', 'name' => 'Irlande'),
            array('id' => 'IS', 'name' => 'Islande'),
            array('id' => 'IL', 'name' => 'Israël'),
            array('id' => 'IT', 'name' => 'Italie'),
            array('id' => 'JM', 'name' => 'Jamaïque'),
            array('id' => 'JP', 'name' => 'Japon'),
            array('id' => 'JE', 'name' => 'Jersey'),
            array('id' => 'JO', 'name' => 'Jordanie'),
            array('id' => 'KZ', 'name' => 'Kazakhstan'),
            array('id' => 'KE', 'name' => 'Kenya'),
            array('id' => 'KG', 'name' => 'Kirghizistan'),
            array('id' => 'KI', 'name' => 'Kiribati'),
            array('id' => 'KW', 'name' => 'Koweït'),
            array('id' => 'LA', 'name' => 'Laos'),
            array('id' => 'LS', 'name' => 'Lesotho'),
            array('id' => 'LV', 'name' => 'Lettonie'),
            array('id' => 'LB', 'name' => 'Liban'),
            array('id' => 'LY', 'name' => 'Libye'),
            array('id' => 'LR', 'name' => 'Libéria'),
            array('id' => 'LI', 'name' => 'Liechtenstein'),
            array('id' => 'LT', 'name' => 'Lituanie'),
            array('id' => 'LU', 'name' => 'Luxembourg'),
            array('id' => 'MK', 'name' => 'Macédoine'),
            array('id' => 'MG', 'name' => 'Madagascar'),
            array('id' => 'MY', 'name' => 'Malaisie'),
            array('id' => 'MW', 'name' => 'Malawi'),
            array('id' => 'MV', 'name' => 'Maldives'),
            array('id' => 'ML', 'name' => 'Mali'),
            array('id' => 'MT', 'name' => 'Malte'),
            array('id' => 'MA', 'name' => 'Maroc'),
            array('id' => 'MQ', 'name' => 'Martinique'),
            array('id' => 'MU', 'name' => 'Maurice'),
            array('id' => 'MR', 'name' => 'Mauritanie'),
            array('id' => 'YT', 'name' => 'Mayotte'),
            array('id' => 'MX', 'name' => 'Mexique'),
            array('id' => 'MD', 'name' => 'Moldavie'),
            array('id' => 'MC', 'name' => 'Monaco'),
            array('id' => 'MN', 'name' => 'Mongolie'),
            array('id' => 'MS', 'name' => 'Montserrat'),
            array('id' => 'ME', 'name' => 'Monténégro'),
            array('id' => 'MZ', 'name' => 'Mozambique'),
            array('id' => 'MM', 'name' => 'Myanmar'),
            array('id' => 'NA', 'name' => 'Namibie'),
            array('id' => 'NR', 'name' => 'Nauru'),
            array('id' => 'NI', 'name' => 'Nicaragua'),
            array('id' => 'NE', 'name' => 'Niger'),
            array('id' => 'NG', 'name' => 'Nigéria'),
            array('id' => 'NU', 'name' => 'Niue'),
            array('id' => 'NO', 'name' => 'Norvège'),
            array('id' => 'NC', 'name' => 'Nouvelle-Calédonie'),
            array('id' => 'NZ', 'name' => 'Nouvelle-Zélande'),
            array('id' => 'NP', 'name' => 'Népal'),
            array('id' => 'OM', 'name' => 'Oman'),
            array('id' => 'UG', 'name' => 'Ouganda'),
            array('id' => 'UZ', 'name' => 'Ouzbékistan'),
            array('id' => 'PK', 'name' => 'Pakistan'),
            array('id' => 'PW', 'name' => 'Palaos'),
            array('id' => 'PA', 'name' => 'Panama'),
            array('id' => 'PG', 'name' => 'Papouasie-Nouvelle-Guinée'),
            array('id' => 'PY', 'name' => 'Paraguay'),
            array('id' => 'NL', 'name' => 'Pays-Bas'),
            array('id' => 'PH', 'name' => 'Philippines'),
            array('id' => 'PN', 'name' => 'Pitcairn'),
            array('id' => 'PL', 'name' => 'Pologne'),
            array('id' => 'PF', 'name' => 'Polynésie française'),
            array('id' => 'PR', 'name' => 'Porto Rico'),
            array('id' => 'PT', 'name' => 'Portugal'),
            array('id' => 'PE', 'name' => 'Pérou'),
            array('id' => 'QA', 'name' => 'Qatar'),
            array('id' => 'HK', 'name' => 'R.A.S. chinoise de Hong Kong'),
            array('id' => 'MO', 'name' => 'R.A.S. chinoise de Macao'),
            array('id' => 'RO', 'name' => 'Roumanie'),
            array('id' => 'GB', 'name' => 'Royaume-Uni'),
            array('id' => 'RU', 'name' => 'Russie'),
            array('id' => 'RW', 'name' => 'Rwanda'),
            array('id' => 'CF', 'name' => 'République centrafricaine'),
            array('id' => 'DO', 'name' => 'République dominicaine'),
            array('id' => 'CD', 'name' => 'République démocratique du Congo'),
            array('id' => 'CZ', 'name' => 'République tchèque'),
            array('id' => 'RE', 'name' => 'Réunion'),
            array('id' => 'EH', 'name' => 'Sahara occidental'),
            array('id' => 'BL', 'name' => 'Saint-Barthélémy'),
            array('id' => 'KN', 'name' => 'Saint-Kitts-et-Nevis'),
            array('id' => 'SM', 'name' => 'Saint-Marin'),
            array('id' => 'MF', 'name' => 'Saint-Martin'),
            array('id' => 'PM', 'name' => 'Saint-Pierre-et-Miquelon'),
            array('id' => 'VC', 'name' => 'Saint-Vincent-et-les Grenadines'),
            array('id' => 'SH', 'name' => 'Sainte-Hélène'),
            array('id' => 'LC', 'name' => 'Sainte-Lucie'),
            array('id' => 'WS', 'name' => 'Samoa'),
            array('id' => 'AS', 'name' => 'Samoa américaines'),
            array('id' => 'ST', 'name' => 'Sao Tomé-et-Principe'),
            array('id' => 'RS', 'name' => 'Serbie'),
            array('id' => 'CS', 'name' => 'Serbie-et-Monténégro'),
            array('id' => 'SC', 'name' => 'Seychelles'),
            array('id' => 'SL', 'name' => 'Sierra Leone'),
            array('id' => 'SG', 'name' => 'Singapour'),
            array('id' => 'SK', 'name' => 'Slovaquie'),
            array('id' => 'SI', 'name' => 'Slovénie'),
            array('id' => 'SO', 'name' => 'Somalie'),
            array('id' => 'SD', 'name' => 'Soudan'),
            array('id' => 'LK', 'name' => 'Sri Lanka'),
            array('id' => 'CH', 'name' => 'Suisse'),
            array('id' => 'SR', 'name' => 'Suriname'),
            array('id' => 'SE', 'name' => 'Suède'),
            array('id' => 'SJ', 'name' => 'Svalbard et Île Jan Mayen'),
            array('id' => 'SZ', 'name' => 'Swaziland'),
            array('id' => 'SY', 'name' => 'Syrie'),
            array('id' => 'SN', 'name' => 'Sénégal'),
            array('id' => 'TJ', 'name' => 'Tadjikistan'),
            array('id' => 'TZ', 'name' => 'Tanzanie'),
            array('id' => 'TW', 'name' => 'Taïwan'),
            array('id' => 'TD', 'name' => 'Tchad'),
            array('id' => 'TF', 'name' => 'Terres australes françaises'),
            array('id' => 'IO', 'name' => 'Territoire britannique de l\'océan Indien'),
            array('id' => 'PS', 'name' => 'Territoire palestinien'),
            array('id' => 'TH', 'name' => 'Thaïlande'),
            array('id' => 'TL', 'name' => 'Timor oriental'),
            array('id' => 'TG', 'name' => 'Togo'),
            array('id' => 'TK', 'name' => 'Tokelau'),
            array('id' => 'TO', 'name' => 'Tonga'),
            array('id' => 'TT', 'name' => 'Trinité-et-Tobago'),
            array('id' => 'TN', 'name' => 'Tunisie'),
            array('id' => 'TM', 'name' => 'Turkménistan'),
            array('id' => 'TR', 'name' => 'Turquie'),
            array('id' => 'TV', 'name' => 'Tuvalu'),
            array('id' => 'UA', 'name' => 'Ukraine'),
            array('id' => 'UY', 'name' => 'Uruguay'),
            array('id' => 'VU', 'name' => 'Vanuatu'),
            array('id' => 'VE', 'name' => 'Venezuela'),
            array('id' => 'VN', 'name' => 'Viêt Nam'),
            array('id' => 'WF', 'name' => 'Wallis-et-Futuna'),
            array('id' => 'YE', 'name' => 'Yémen'),
            array('id' => 'ZM', 'name' => 'Zambie'),
            array('id' => 'ZW', 'name' => 'Zimbabwe'),
            array('id' => 'ZZ', 'name' => 'région indéterminée'),
            array('id' => 'EG', 'name' => 'Égypte'),
            array('id' => 'AE', 'name' => 'Émirats arabes unis'),
            array('id' => 'EC', 'name' => 'Équateur'),
            array('id' => 'ER', 'name' => 'Érythrée'),
            array('id' => 'VA', 'name' => 'État de la Cité du Vatican'),
            array('id' => 'FM', 'name' => 'États fédérés de Micronésie'),
            array('id' => 'US', 'name' => 'États-Unis'),
            array('id' => 'ET', 'name' => 'Éthiopie'),
            array('id' => 'BV', 'name' => 'Île Bouvet'),
            array('id' => 'CX', 'name' => 'Île Christmas'),
            array('id' => 'NF', 'name' => 'Île Norfolk'),
            array('id' => 'IM', 'name' => 'Île de Man'),
            array('id' => 'KY', 'name' => 'Îles Caïmans'),
            array('id' => 'CC', 'name' => 'Îles Cocos - Keeling'),
            array('id' => 'CK', 'name' => 'Îles Cook'),
            array('id' => 'FO', 'name' => 'Îles Féroé'),
            array('id' => 'HM', 'name' => 'Îles Heard et MacDonald'),
            array('id' => 'FK', 'name' => 'Îles Malouines'),
            array('id' => 'MP', 'name' => 'Îles Mariannes du Nord'),
            array('id' => 'MH', 'name' => 'Îles Marshall'),
            array('id' => 'UM', 'name' => 'Îles Mineures Éloignées des États-Unis'),
            array('id' => 'SB', 'name' => 'Îles Salomon'),
            array('id' => 'TC', 'name' => 'Îles Turks et Caïques'),
            array('id' => 'VG', 'name' => 'Îles Vierges britanniques'),
            array('id' => 'VI', 'name' => 'Îles Vierges des États-Unis'),
            array('id' => 'AX', 'name' => 'Îles Åland')
        );

        foreach($countries as $country){
            Country::create($country);
        }
    }
}
