<?php

use Illuminate\Database\Seeder;
use App\Genre;

class GenresTableSeeder extends Seeder
{
    function run()
    {
        DB::table('genres')->truncate();

        $genres = array(
            array('name' => 'Blues'),
            array('name' => 'Classic Rock'),
            array('name' => 'Country'),
            array('name' => 'Dance'),
            array('name' => 'Disco'),
            array('name' => 'Funk'),
            array('name' => 'Grunge'),
            array('name' => 'Hip-Hop'),
            array('name' => 'Jazz'),
            array('name' => 'Metal'),
            array('name' => 'New Age'),
            array('name' => 'Oldies'),
            array('name' => 'Other'),
            array('name' => 'Pop'),
            array('name' => 'R&B'),
            array('name' => 'Rap'),
            array('name' => 'Reggae'),
            array('name' => 'Rock'),
            array('name' => 'Techno'),
            array('name' => 'Industrial'),
            array('name' => 'Alternative'),
            array('name' => 'Ska'),
            array('name' => 'Death Metal'),
            array('name' => 'Pranks'),
            array('name' => 'Soundtrack'),
            array('name' => 'Euro-Techno'),
            array('name' => 'Ambient'),
            array('name' => 'Trip-Hop'),
            array('name' => 'Vocal'),
            array('name' => 'Jazz+Funk'),
            array('name' => 'Fusion'),
            array('name' => 'Trance'),
            array('name' => 'Classical'),
            array('name' => 'Instrumental'),
            array('name' => 'Acid'),
            array('name' => 'House'),
            array('name' => 'Game'),
            array('name' => 'Sound Clip'),
            array('name' => 'Gospel'),
            array('name' => 'Noise'),
            array('name' => 'AlternRock'),
            array('name' => 'Bass'),
            array('name' => 'Soul'),
            array('name' => 'Punk'),
            array('name' => 'Space'),
            array('name' => 'Meditative'),
            array('name' => 'Instrumental Pop'),
            array('name' => 'Instrumental Rock'),
            array('name' => 'Ethnic'),
            array('name' => 'Gothic'),
            array('name' => 'Darkwave'),
            array('name' => 'Techno-Industrial'),
            array('name' => 'Electronic'),
            array('name' => 'Pop-Folk'),
            array('name' => 'Eurodance'),
            array('name' => 'Dream'),
            array('name' => 'Southern Rock'),
            array('name' => 'Comedy'),
            array('name' => 'Cult'),
            array('name' => 'Gangsta Rap'),
            array('name' => 'Top 40'),
            array('name' => 'Christian Rap'),
            array('name' => 'Pop / Funk'),
            array('name' => 'Jungle'),
            array('name' => 'Native American'),
            array('name' => 'Cabaret'),
            array('name' => 'New Wave'),
            array('name' => 'Psychedelic'),
            array('name' => 'Rave'),
            array('name' => 'Showtunes'),
            array('name' => 'Trailer'),
            array('name' => 'Lo-Fi'),
            array('name' => 'Tribal'),
            array('name' => 'Acid Punk'),
            array('name' => 'Acid Jazz'),
            array('name' => 'Polka'),
            array('name' => 'Retro'),
            array('name' => 'Musical'),
            array('name' => 'Rock & Roll'),
            array('name' => 'Hard Rock'),
            array('name' => 'Folk'),
            array('name' => 'Folk-Rock'),
            array('name' => 'National Folk'),
            array('name' => 'Swing'),
            array('name' => 'Fast  Fusion'),
            array('name' => 'Bebob'),
            array('name' => 'Latin'),
            array('name' => 'Revival'),
            array('name' => 'Celtic'),
            array('name' => 'Bluegrass'),
            array('name' => 'Avantgarde'),
            array('name' => 'Gothic Rock'),
            array('name' => 'Progressive Rock'),
            array('name' => 'Psychedelic Rock'),
            array('name' => 'Symphonic Rock'),
            array('name' => 'Slow Rock'),
            array('name' => 'Big Http'),
            array('name' => 'Chorus'),
            array('name' => 'Easy Listening'),
            array('name' => 'Acoustic'),
            array('name' => 'Humour'),
            array('name' => 'Speech'),
            array('name' => 'Chanson'),
            array('name' => 'Opera'),
            array('name' => 'Chamber Music'),
            array('name' => 'Sonata'),
            array('name' => 'Symphony'),
            array('name' => 'Booty Bass'),
            array('name' => 'Primus'),
            array('name' => 'Porn Groove'),
            array('name' => 'Satire'),
            array('name' => 'Slow Jam'),
            array('name' => 'Club'),
            array('name' => 'Tango'),
            array('name' => 'Samba'),
            array('name' => 'Folklore'),
            array('name' => 'Ballad'),
            array('name' => 'Power Ballad'),
            array('name' => 'Rhythmic Soul'),
            array('name' => 'Freestyle'),
            array('name' => 'Duet'),
            array('name' => 'Punk Rock'),
            array('name' => 'Drum Solo'),
            array('name' => 'A Cappella'),
            array('name' => 'Euro-House'),
            array('name' => 'Dance Hall'),
            array('name' => 'Goa'),
            array('name' => 'Drum & Bass'),
            array('name' => 'Club-House'),
            array('name' => 'Hardcore'),
            array('name' => 'Terror'),
            array('name' => 'Indie'),
            array('name' => 'BritPop'),
            array('name' => 'Negerpunk'),
            array('name' => 'Polsk Punk'),
            array('name' => 'Beat'),
            array('name' => 'Christian Gangsta Rap'),
            array('name' => 'Heavy Metal'),
            array('name' => 'Black Metal'),
            array('name' => 'Crossover'),
            array('name' => 'Contemporary Christian	'),
            array('name' => 'Christian Rock'),
            array('name' => 'Merengue'),
            array('name' => 'Salsa'),
            array('name' => 'Thrash Metal'),
            array('name' => 'Anime'),
            array('name' => 'JPop'),
            array('name' => 'Synthpop'),
            array('name' => 'Rock/Pop')
        );

        foreach($genres as $genre){
            Genre::create($genre);
        }
    }
}
